### ISSUE TITLE
Add automated testing against PostgreSQL 9.6

### ISSUE THREAD

**Issue by strk** [pgpointcloud/pointcloud#156]
Current travis only tests runs against PostgreSQL 9.3, it'd be useful to have more versions tested too.

**Comment by elemoine** [comment]
Agree. Do you think we should run the test suite on multiple PostgreSQL versions? Or should we just run it on 9.6?

**Comment by strk** [comment]
Ideally it'll be on multiple versions.
I think Travis doesn't support more recent versions by default so
either we use pre-built dockers for testing (would be faster)
or we build PostgreSQL as part of the job.

**Comment by elemoine** [comment]
It looks like PostgreSQL 9.6 is available for Trusty. See https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version.

**Comment by strk** [comment]
We need the development files, not just the runtime service (see how postgresql-server-dev-9.3 is installed in .travis.yml)

**Comment by elemoine** [comment]
Yep, got it.

**Comment by robe2** [comment]
You can always use apt.postgresql.org for any testing.  They have both the regular postgresql-server and postgresql-server-dev files and for lots of versions.  I think that should work for travis fine since it's ubuntu.  Here are instructions - 

https://trac.osgeo.org/postgis/wiki/UsersWikiPostGIS23UbuntuPGSQL96Apt

Then for postgresql 9.6 would be:

`sudo apt-get install postgresql-9.6 postgresql-server-dev-9.6 postgresql-9.6-postgis-2.3 postgresql-contrib-9.6`

Guess you don't need the postgis part unless we do postgis testing of the pointcloud-postgis extension.

**Comment by pblottiere** [comment]
Considering that  [this](https://github.com/pgpointcloud/pointcloud/pull/210) PR has been merged, I think we can close this issue now.
