### ISSUE TITLE
Provide PC_GetAll returning full values array

### ISSUE THREAD

**Issue by strk** [pgpointcloud/pointcloud#38]
The return value could be used as the second argument to PC_MakePoint to convert from a pcid to another (for example).

**Comment by Remi-C** [comment]
Hey,
I tried to do exactly this.
My goal was first to avoid multiple pc_get calls (with 22 attributes, it is
annoying),

the important side bonus was attribute reduction.
Most of the time user need only few attributes (like X,Y,Z,Intensity).
Currently all attributes are manipulated and keept until the call to pc_get.
I made changes so that the user can ask a patch with a reduced number of
attributes (dimensions).
Of course because efficiency is the goal, we discard attributes the soonest
possible.

I called it "alternate_explode" because at the end, it provides a more
efficient way to get data.
It is here :
https://github.com/Remi-C/pointcloud/tree/alternate_explode
(for a diff :
https://github.com/Remi-C/pointcloud/compare/pgpointcloud:master...master)

It worked, and I noticed improve of about 30% of speed in my use case, (and
the advantage and not writing a lot of pc_get).
I hit some trouble with cache I think, because calling numerous time the
new functions was crashing the server at a point.

Anyway I never commited because I feel my code, altough unit tested, is not
up to the standard of pgpointcloud.

Cheers,
Rémi-C

2015-02-04 12:34 GMT+01:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
actually my goal was typing less while converting points from one schema to another. surely the ability to specify _which_ dimension to get in the returning ARRAY is useful, as long as I can ask "all" of them.

In any case I need a function that returns an ARRAY of numbers, to use for creating a differently-formatted pcpoint (and finally pcpatch from the set of pcpoints). This is the scope of this ticket. I suggest you to file another ticket or PR for your enhanced expoder.

**Comment by Remi-C** [comment]
Hm,
it is precisely what I did :

--one call to get the dim you want--
CREATE OR REPLACE FUNCTION pc_get(pt pcpoint, dimnames text[])
  RETURNS double precision[] AS
'$libdir/pointcloud', 'pcpoint_get_values'

--one call to get everything as double array--
CREATE OR REPLACE FUNCTION pc_get_all(p pcpoint)
  RETURNS SETOF double precision[] AS
'$libdir/pointcloud', 'pcpoint_get_all_values'

Cheers,
Rémi-C

2015-02-05 11:41 GMT+01:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
Ah, I must have missed that from your tree. 
Had you tried to use just PC_Get(pcpoint) for the "get_all" approach ?
That way there'd be a single name for all 3 flavors. Not sure if there are problems with that.
Also, I think PC_GetAll would be more in style with the rest of functions, if PC_Get(pcpoint) is not feasible.

What about a PR with just this new function and tests ?

Another thing that I wonder is if specifying dimension by index rather than by name would make things any faster.

**Comment by Remi-C** [comment]
I think you are right for names,
it is an easy change because only plpgsql declaration of the function
changes (not the C lib or C wrapper).
There are no problems because  pc_get(pcpoint, text) and pc_get(pcpoint)
don't have the same arguments.

I'm not fluent with git,
including only pc_get(pcpoint) is very small and require only few dozen of
lines in 3 files (+ writting a separate test, which should be easy enough)

what would be easiest ?

update pointcloud to latest (might conflict with changes I did on my
master), then create a branch from it, then add the changes to this branch,
then PR?

I don't know how to isolate all my changes to start fresh from current
pointcloud version.

Cheers,
Rémi-C


2015-02-05 12:39 GMT+01:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
You can put your changes into a branch, then reset your "master"
to be the same as original master.

Then, you can create a _new_ branch where you'd put the pc_get changes
only. You could pick changes either manually or via git cherry-pick
if commits exist that only add those functions. Manually is maybe easier

**Comment by strk** [comment]
@Remi-C are you planning to provide the PR ? Or I'll take a look at extracting the commit from your tree...

**Comment by strk** [comment]
I've pushed the library side of this as 225327468dcd892d0be5eaec09d929b0ac3d834f

**Comment by Remi-C** [comment]
Hum it's actually embarrassing,
I had a lot of troubles to perform the git part

What I am doing :
 - use this web page
<https://github.com/Remi-C/pointcloud/compare/pgpointcloud:master...alternate_explode>
to see the changes
 - create a new branch from current upstream master, called pc_get_all
 - untrack this branch, and push it to my fork
 - then collect the necessary change and past theim
 - use QTCreator to check that everything compile fine and write the
missing test

Cheers,
Rémi-C

2015-02-12 10:37 GMT+01:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
I suggest you want a few hours before proceeding as I'm in the process
of pushing the PC_Get() signature taking a single parameter and returning
an array.

What's left in your branch is the version of the function taking an array
of dimension names, and the alternate explode itself.

**Comment by strk** [comment]
I noticed your PC_Get_All is returning an array of FLOAT8 while PC_Get is returning a numeric instead.

I'm happy with the FLOAT8 but wondering why the other one is using NUMERIC.
@pramsey was there any reason to pick "numeric" over "float8" ?

**Comment by Remi-C** [comment]
Ok,
I finished writing the test and including changes.
Let me know what to do next.
I think I successively isolated the changes to add the function in this
branch and in this commit :
https://github.com/Remi-C/pointcloud/commit/98d1aafb27bc4eebf6309ee979e5873cff607fe8

Cheers,
Rémi-C

2015-02-12 11:53 GMT+01:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
Remi, as of 2ecca0b602670d68da293807501ec9fc2b8121f7 master has the new PC_Get(pcpoint) function. I think I'm happy with this for this ticket, except for the versioning which is likely to need a separate ticket on its own.

**Comment by Remi-C** [comment]
Very good to have this function, it saves a tone of writing time (and maybe
a little bit faster, but not sure) !

For versionning,
it would be good to have the same system as postgis :
a script from 1.0 to 1.0next, and a script from 1.0next to 1.0 ?

Cheers,
Rémi-C


2015-02-12 12:11 GMT+01:00 Sandro Santilli <notifications@github.com>:
